version: '3'
services:
  app:
    image: larahack/linkflows_model_app
    restart: always
    ports:
      - "8081:8081"
  db:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    restart: always
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
      DBA_PASSWORD: "admin"
    volumes:
      - ./data/virtuoso:/data
    # ports:
    #   - "18890:8890"
  client:
    image: larahack/linkflows_interface
    restart: always
    ports:
      - "18070:80"
