version: '2'
services:
  app:
    image: linkflows
    ports:
      - "8081:8081"
  db:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
      DBA_PASSWORD: "admin"
    volumes:
      - ./data/virtuoso:/data
    ports:
      - "8890:8890"
  client:
    image: linkflows_interface
    ports:
      - "80:80"
